networks:
  default:
    external:
      name: dy
services:
  db:
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_DB=db
    image: quay.io/akretion/postgresql:10
    volumes:
      - .db/:/var/lib/postgresql/data
  odoo:
    build: odoo
    environment:
      - PYTHONDONTWRITEBYTECODE=True
      - LOCAL_USER_ID=$UID
      - DB_USER=odoo
      - DB_PASS=odoo
      - DB_NAME=db
      - DB_HOST=db
      - RUNNING_ENV=dev
      - VIRTUAL_HOST=douze.dy
      - VIRTUAL_PORT=8069
      - DEMO=True
      - WORKERS=0
      - LIMIT_TIME_CPU=600
      - LIMIT_TIME_REAL=800
    links:
      - db
    networks:
      default:
        aliases:
          - shopinvader-docky.dy
    volumes:
      - ./odoo:/odoo
      - ./data/addons:/data/odoo/addons
      - ./data/filestore:/data/odoo/filestore
      - ./data/sessions:/data/odoo/sessions
    links:
      - db
      # - adminer
  # adminer:
  #   image: adminer
  #   environment:
  #     - QUERY_PARAMETER=/?pgsql=db&username=odoo&db=db
  #     - VIRTUAL_HOST=adminer.lfg.dy
  #     - VIRTUAL_PORT=8080
  #     - ADMINER_PLUGINS=tables-filter
  #     - ADMINER_DESIGN=rmsoft
  #   links:
  #     - db
version: '3'
