networks:
  default:
    external:
      name: dy
services:
  db:
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_DB=db
    image: quay.io/akretion/postgresql:10
    volumes:
      - .db/:/var/lib/postgresql/data
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    environment:
      - discovery.type=single-node
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    labels:
      traefik.www.frontend.rule: "Host:demo-elastic.dy"
  odoo:
    build: odoo
    environment:
      - PYTHONDONTWRITEBYTECODE=True
      - LOCAL_USER_ID=$UID
      - DB_USER=odoo
      - DB_PASS=odoo
      - DB_NAME=db
      - DB_HOST=db
      - RUNNING_ENV=dev
      - MARABUNTA_MODE=demo
      - DEMO=True
      - SERVER_WIDE_MODULES=web,web_kanban,queue_job
    links:
      - db
      - elastic
    labels:
      traefik.longpolling.frontend.rule: "Host:demo-odoo.dy;PathPrefix:/longpolling/"
      traefik.www.frontend.rule: "Host:demo-odoo.dy"
    volumes:
      - ./odoo:/odoo
      - ./data/addons:/data/odoo/addons
      - ./data/filestore:/data/odoo/filestore
      - ./data/sessions:/data/odoo/sessions
version: '3'
