#!/bin/bash

if [ "$( psql -tAc "SELECT to_regclass('shopinvader_backend')" )" != 'shopinvader_backend' ]
then
    echo "Database does not exist"
    if [ -f /backup/db.sql ]
    then
        echo "Load database backup"
        dropdb $PGDATABASE --if-exists
        createdb $PGDATABASE
        psql $PGDATABASE -f /backup/db.sql >/dev/null
        cp -r /backup/filestore/* /data/odoo/filestore
        chown -R odoo:odoo /data/odoo/filestore
    else
        echo "Database backup do not exist create it"
    fi
else
    echo "Database already exist"
fi
